# Site Configuration
title: Igoc
description: Developer Blog
url: "https://Igoc.github.io"
baseurl: ""
repository: "Igoc/Igoc.github.io"

google_site_verification: "X-pOPUaqQLZEtSUSnzhtqFNtq3odCgPOs4cvgdPYEmo"
naver_site_verification: "851b5187a818cb269867ce35a2963a0816773037"

# Author Configuration
author:
    name: "류상수"
    avatar: "https://avatars.githubusercontent.com/u/22683489?v=4"
    bio: "개발자 블로그"
    links:
        - label: "Email"
          icon: "fas fa-fw fa-envelope-square"
          url: "mailto:zx0342@gmail.com"
        - label: "GitHub"
          icon: "fab fa-fw fa-github"
          url: "https://github.com/Igoc"

# Analytics Configuration
analytics:
    provider: "google-gtag"
    google:
        tracking_id: "G-TS0SD2BT7E"
        anonymize_ip: false

# Comments Configuration
comments:
    provider: "utterances"
    utterances:
        theme: "github-light"
        issue_term: "pathname"
        label: "Comment"

# Theme Configuration
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

atom_feed:
    hide: true

# Outputting Configuration
permalink: /:categories/:title/

paginate: 5
paginate_path: /page:num/

# Archive Configuration
category_archive:
    type: liquid
    path: /category/

# File Configuration
include:
    - _pages

# Front Matter Defaults Configuration
defaults:
    - scope:
          path: ""
          type: posts
      values:
          layout: single
          author_profile: true
          sidebar_category: true
          comments: true
    - scope:
          path: ""
          type: pages
      values:
          author_profile: true
          sidebar_category: true

# Plugin Configuration
plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-include-cache
    - jekyll-paginate

whitelist:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-include-cache
    - jekyll-paginate