# Site Configuration
title: Igoc
description: Development Blog
url: ""
baseurl: ""

# Social Configuration
email: zx0342@gmail.com

github:
    username: Igoc

# Theme Configuration
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

atom_feed:
    hide: true

# Plugin Configuration
plugins:
    - jekyll-feed
    - jekyll-include-cache