# Site Configuration
title: Igoc
description: Development Blog
url: ""
baseurl: ""

# Social Configuration
email: zx0342@gmail.com

github:
    username: Igoc

# Plugin Configuration
plugins:
    - jekyll-feed