# Site Configuration
title: Igoc
description: Developer Blog
url: ""
baseurl: ""

# Author Configuration
author:
    name: "류상수"
    avatar: "https://avatars.githubusercontent.com/u/22683489?v=4"
    bio: "개발자 블로그"
    links:
        - label: "Email"
          icon: "fas fa-fw fa-envelope-square"
          url: "mailto:zx0342@gmail.com"
        - label: "GitHub"
          icon: "fab fa-fw fa-github"
          url: "https://github.com/Igoc"

# Theme Configuration
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

atom_feed:
    hide: true

# Outputting Configuration
permalink: /:categories/:title/

# Archive Configuration
category_archive:
    type: liquid
    path: /category/

# File Configuration
include:
    - _pages

# Front Matter Defaults Configuration
defaults:
    - scope:
          path: ""
          type: posts
      values:
          layout: single
          author_profile: true
          sidebar_category: true
    - scope:
          path: ""
          type: pages
      values:
          author_profile: true
          sidebar_category: true

# Plugin Configuration
plugins:
    - jekyll-feed
    - jekyll-include-cache